server:
  port: 8080

spring:
  dubbo:
    application:
      name: provider
    server: true
    registry:
      address: zookeeper://192.168.151.140:2181
    protocol:
      name: dubbo
      port: 20880