server:
  port: 8080

dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://zookeeper:2181
    timeout: 2000
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false
    loadbalance: roundrobin
  config-center:
    timeout: 2000