server:
  port: 8081

dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://192.168.151.141:2181
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false
    loadbalance: roundrobin

