server:
  port: 8081

spring:
  dubbo:
    application:
      name: consumer
    registry:
      address: zookeeper://192.168.151.140:2181
    protocol:
      name: dubbo
      port: 20880
    consumer:
      check: false
    reference:
      loadbalance: roundrobin

